inclue /home/son/.config/kitty/kitty-themes/themes/Github.conf

font_family JetBrains Mono
font_size 11
shell_integration no-cursor

remember_window_size  no
initial_window_width  640
initial_window_height 400

map ctrl+shift+n new_os_window_with_cwd
